apiVersion: v1
kind: ConfigMap
metadata:
  name: aks-workflow-webapi-deployment-config
  namespace: namespace-workflow-1783267916431
  labels:
    app.kubernetes.io/name: aks-workflow-webapi-deployment
    kubernetes.azure.com/generator: devhub
data: