apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aks-workflow-webapi-deployment
  labels:
    app.kubernetes.io/name: aks-workflow-webapi-deployment
    app.kubernetes.io/part-of: aks-workflow-webapi-deployment-project
    kubernetes.azure.com/generator: devhub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aks-workflow-webapi-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80