apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aks-workflow-webapi-deployment
  labels:
    app.kubernetes.io/name: aks-workflow-webapi-deployment
    app.kubernetes.io/part-of: aks-workflow-webapi-deployment-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: aks-workflow-webapi-deployment